//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leen.Media.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leen.Media.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 媒体时长不应长于原始时长 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_DurationShouldNotBiggerThanNatrualDuration {
            get {
                return ResourceManager.GetString("STR_ERR_DurationShouldNotBiggerThanNatrualDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体导出尚未完成 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_ExportingExists {
            get {
                return ResourceManager.GetString("STR_ERR_ExportingExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出会话创建失败 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_ExportSessionNotCreated {
            get {
                return ResourceManager.GetString("STR_ERR_ExportSessionNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体导出进度不应小于零或大于导出时长 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_InvalidPositionOfExporting {
            get {
                return ResourceManager.GetString("STR_ERR_InvalidPositionOfExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染尺寸无效 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_InvalidRenderSize {
            get {
                return ResourceManager.GetString("STR_ERR_InvalidRenderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体已打开 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_MediaAlreadyOpened {
            get {
                return ResourceManager.GetString("STR_ERR_MediaAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体未能初始化 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_MediaCanNotInitialize {
            get {
                return ResourceManager.GetString("STR_ERR_MediaCanNotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体对象已被释放 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_MediaDisposed {
            get {
                return ResourceManager.GetString("STR_ERR_MediaDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体播放未打开 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_MediaNotOpen {
            get {
                return ResourceManager.GetString("STR_ERR_MediaNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流媒体服务器不可用 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_MediaServerUnavailable {
            get {
                return ResourceManager.GetString("STR_ERR_MediaServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体会话创建失败 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_MediaSessionNotCreated {
            get {
                return ResourceManager.GetString("STR_ERR_MediaSessionNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体导出不存在 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_NoExportingExists {
            get {
                return ResourceManager.GetString("STR_ERR_NoExportingExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体播放进度不应小于零 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_PositionShouldBiggerThanZero {
            get {
                return ResourceManager.GetString("STR_ERR_PositionShouldBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算机硬件不支持 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_UnsupportedHardware {
            get {
                return ResourceManager.GetString("STR_ERR_UnsupportedHardware", resourceCulture);
            }
        }
    }
}
