//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leen.Media.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leen.Media.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 帧退 的本地化字符串。
        /// </summary>
        internal static string STR_Command_FrameBackwards {
            get {
                return ResourceManager.GetString("STR_Command_FrameBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帧进 的本地化字符串。
        /// </summary>
        internal static string STR_Command_FrameForwards {
            get {
                return ResourceManager.GetString("STR_Command_FrameForwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停导出 的本地化字符串。
        /// </summary>
        internal static string STR_Command_PauseExport {
            get {
                return ResourceManager.GetString("STR_Command_PauseExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒播 的本地化字符串。
        /// </summary>
        internal static string STR_Command_PlayBackwards {
            get {
                return ResourceManager.GetString("STR_Command_PlayBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常播放 的本地化字符串。
        /// </summary>
        internal static string STR_Command_ResumePlay {
            get {
                return ResourceManager.GetString("STR_Command_ResumePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始导出 的本地化字符串。
        /// </summary>
        internal static string STR_Command_StartExport {
            get {
                return ResourceManager.GetString("STR_Command_StartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止导出 的本地化字符串。
        /// </summary>
        internal static string STR_Command_StopExport {
            get {
                return ResourceManager.GetString("STR_Command_StopExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图 的本地化字符串。
        /// </summary>
        internal static string STR_Command_TakeSnapshot {
            get {
                return ResourceManager.GetString("STR_Command_TakeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续截图 的本地化字符串。
        /// </summary>
        internal static string STR_Command_TakeSnapshots {
            get {
                return ResourceManager.GetString("STR_Command_TakeSnapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放/暂停 的本地化字符串。
        /// </summary>
        internal static string STR_Command_TogglePlayPause {
            get {
                return ResourceManager.GetString("STR_Command_TogglePlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        internal static string STR_Command_ZoomIn {
            get {
                return ResourceManager.GetString("STR_Command_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        internal static string STR_Command_ZoomOut {
            get {
                return ResourceManager.GetString("STR_Command_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未打开媒体 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_MediaNotOpened {
            get {
                return ResourceManager.GetString("STR_ERR_MediaNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已打开媒体 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_MediaOpened {
            get {
                return ResourceManager.GetString("STR_ERR_MediaOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未完成控件初始化 的本地化字符串。
        /// </summary>
        internal static string STR_ERR_NotInitialized {
            get {
                return ResourceManager.GetString("STR_ERR_NotInitialized", resourceCulture);
            }
        }
    }
}
